import Config

# Configure your database
config :strangertalks_new, StrangertalksNew.Repo,
  username: "postgres",
  password: System.get_env("STRANGERTALKS_LOCAL_DB_PASSWORD"),
  hostname: "localhost",
  database: "strangertalks_new_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: false,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :strangertalks_new, StrangertalksNewWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: ["http://localhost:4000", "http://127.0.0.1:4000"],
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3Kyi6grdj8kYl0aS7hosCsIT11xzQ+zaWskcydbdet6BLX5wO3GjTTfbWqFpCSHo",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :strangertalks_new, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $metadata$message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Development C11 Policy Fixture (Local Development & Browser E2E)
config :strangertalks_new, :c11_policy,
  quotas_verified: true,
  primary_available: true,
  fallback_available: true,
  max_fallback_reservations: 10,
  credential_ttl_seconds: 300,
  usage_snapshot: %{usage_count: 0, budget_limit: 100}
